
package utilserviceImple.UtilServiceImple;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UtilServiceImplService", targetNamespace = "http://serviceImpl/", wsdlLocation = "http://localhost:8087/proyecto.DSD.Server/?wsdl")
public class UtilServiceImplService
    extends Service
{

    private final static URL UTILSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException UTILSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName UTILSERVICEIMPLSERVICE_QNAME = new QName("http://serviceImpl/", "UtilServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8087/proyecto.DSD.Server/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UTILSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        UTILSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UtilServiceImplService() {
        super(__getWsdlLocation(), UTILSERVICEIMPLSERVICE_QNAME);
    }

    public UtilServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UTILSERVICEIMPLSERVICE_QNAME, features);
    }

    public UtilServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, UTILSERVICEIMPLSERVICE_QNAME);
    }

    public UtilServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UTILSERVICEIMPLSERVICE_QNAME, features);
    }

    public UtilServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtilServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UtilServiceImpl
     */
    @WebEndpoint(name = "UtilServiceImplPort")
    public UtilServiceImpl getUtilServiceImplPort() {
        return super.getPort(new QName("http://serviceImpl/", "UtilServiceImplPort"), UtilServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtilServiceImpl
     */
    @WebEndpoint(name = "UtilServiceImplPort")
    public UtilServiceImpl getUtilServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceImpl/", "UtilServiceImplPort"), UtilServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UTILSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw UTILSERVICEIMPLSERVICE_EXCEPTION;
        }
        return UTILSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
