
package utilserviceImple.UtilServiceImple;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtilServiceImpl", targetNamespace = "http://serviceImpl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtilServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrarSolicitud", targetNamespace = "http://serviceImpl/", className = "utilserviceImple.UtilServiceImple.RegistrarSolicitud")
    @ResponseWrapper(localName = "registrarSolicitudResponse", targetNamespace = "http://serviceImpl/", className = "utilserviceImple.UtilServiceImple.RegistrarSolicitudResponse")
    @Action(input = "http://serviceImpl/UtilServiceImpl/registrarSolicitudRequest", output = "http://serviceImpl/UtilServiceImpl/registrarSolicitudResponse")
    public Integer registrarSolicitud(
        @WebParam(name = "arg0", targetNamespace = "")
        Solicitud arg0);

    /**
     * 
     * @return
     *     returns java.util.List<utilserviceImple.UtilServiceImple.Cliente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarClientes", targetNamespace = "http://serviceImpl/", className = "utilserviceImple.UtilServiceImple.ListarClientes")
    @ResponseWrapper(localName = "listarClientesResponse", targetNamespace = "http://serviceImpl/", className = "utilserviceImple.UtilServiceImple.ListarClientesResponse")
    @Action(input = "http://serviceImpl/UtilServiceImpl/listarClientesRequest", output = "http://serviceImpl/UtilServiceImpl/listarClientesResponse")
    public List<Cliente> listarClientes();

}
