
package serviceImpl.UtilServiceImpl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UtilService", targetNamespace = "http://serviceImpl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtilService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrarSolicitud", targetNamespace = "http://serviceImpl/", className = "serviceImpl.UtilServiceImpl.RegistrarSolicitud")
    @ResponseWrapper(localName = "registrarSolicitudResponse", targetNamespace = "http://serviceImpl/", className = "serviceImpl.UtilServiceImpl.RegistrarSolicitudResponse")
    public Integer registrarSolicitud(
        @WebParam(name = "arg0", targetNamespace = "")
        Solicitud arg0);

    /**
     * 
     * @return
     *     returns java.util.List<serviceImpl.UtilServiceImpl.Cliente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarClientes", targetNamespace = "http://serviceImpl/", className = "serviceImpl.UtilServiceImpl.ListarClientes")
    @ResponseWrapper(localName = "listarClientesResponse", targetNamespace = "http://serviceImpl/", className = "serviceImpl.UtilServiceImpl.ListarClientesResponse")
    public List<Cliente> listarClientes();

}
